### ISSUE TITLE
[HELP] Issue with tools folder when compiled

### ISSUE THREAD

**Issue by NathanGASC** [TaroEld/BBbuilder#2]
version : 1.0.4 (compiled myself)

The issue which I have here don't happen if I use the release you have done. If I compile the version myself, I have an error when I try to compile my custom mod. When you see french in the errors, it's written "File can't be found".

![image](https://github.com/TaroEld/BBbuilder/assets/36534664/07cb8b3e-6819-44b3-b473-27b0f9935c8b)

From what i've seen, the issue probably come from tools folder when the code try to execute sq.exe (like in [https://github.com/TaroEld/BBbuilder/issues/1](https://github.com/TaroEld/BBbuilder/issues/1) ). As I've sayed in this first issue, I've added manually the tools folder before the compilation.

The tools folder from the release 1.0.4
![image](https://github.com/TaroEld/BBbuilder/assets/36534664/8f20e247-fe63-4596-a271-3b90273b45c4)

The tools folder from the release 1.0.4 compiled by me
![image](https://github.com/TaroEld/BBbuilder/assets/36534664/457bb695-30dc-4aca-95fb-bfcddc98aa90)

Did I miss something ?

**Comment by TaroEld** [comment]
Yeah, with the `produce single file` option under `File publish options` version it eats those files. At some point I just resorted to adding the tools folder to the built zip when packing it. You can also uncheck `produce single file` and it'll copy them over properly. Alternatively, one can do post-build macros to copy them over, but I never bothered. There's probably also other options that I don't know of.
