### ISSUE TITLE
Bug: typo on option "-script[s]only

### ISSUE THREAD

**Issue by Darxo** [TaroEld/BBbuilder#7]
In this line you declare the option `scriptonly`
https://github.com/TaroEld/BBbuilder/blob/2ae26567dd19a394bc82d2458a865d9ef2ae8215/BuildCommand.cs#L22

But in these lines you try to call the option under the name `-scriptsonly`

https://github.com/TaroEld/BBbuilder/blob/2ae26567dd19a394bc82d2458a865d9ef2ae8215/build_template_vs#L37

https://github.com/TaroEld/BBbuilder/blob/2ae26567dd19a394bc82d2458a865d9ef2ae8215/build_template_vs#L47

**Comment by TaroEld** [comment]
Irrelevant now as this option no longer exists
