### ISSUE TITLE
[Request] check data order for presence of this modname

### ISSUE THREAD

**Issue by Darxo** [TaroEld/BBbuilder#9]
I'd like a feature where BBbuilder checks the data folder whether this mod already exists there but with a version number (or any other additional text).
It could then print a warning/error in the log and stop building, as if it encountered a syntax error.

When I do releases, I build the mod, then navigate to my data folder and manually add the correct version number and then send it. Often times I forget about the mod, only to days later realize that now I have two times the same mod in there when I build it again.

But that can also be useful when someone does a mix of downloading the official release with a version number and building it from scratch at a later point.

**Comment by TaroEld** [comment]
Is done
